// ============================================================
//  mock-data.js  —  Shared data for School Management System
//  Include this file in any page that needs application data:
//  <script src="mock-data.js"></script>
// ============================================================

const MOCK_USERS = [
  { id: 1,  name: 'Amara Osei',        email: 'amara.osei@school.edu',       role: 'Student', group: 'Grade 10A',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 001', dob: '2009-03-12' },
  { id: 2,  name: 'David Kimani',       email: 'd.kimani@school.edu',         role: 'Teacher', group: 'Mathematics',    status: 'Active',    joined: 'Aug 2022', phone: '+254 700 111 002', dob: '1985-07-22' },
  { id: 3,  name: 'Fatima Al-Hassan',   email: 'fatima.h@school.edu',         role: 'Student', group: 'Grade 8B',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 003', dob: '2011-01-05' },
  { id: 4,  name: 'Mr. James Otieno',   email: 'j.otieno@school.edu',         role: 'Admin',   group: 'Administration', status: 'Active',    joined: 'Mar 2020', phone: '+254 700 111 004', dob: '1978-11-30' },
  { id: 5,  name: 'Lily Wanjiku',       email: 'lily.w@school.edu',           role: 'Student', group: 'Grade 11C',      status: 'Inactive',  joined: 'Jan 2023', phone: '+254 700 111 005', dob: '2008-06-14' },
  { id: 6,  name: 'Ms. Grace Mwangi',   email: 'g.mwangi@school.edu',         role: 'Teacher', group: 'Science',        status: 'Active',    joined: 'Jan 2021', phone: '+254 700 111 006', dob: '1990-09-18' },
  { id: 7,  name: 'Peter Ndungu',       email: 'p.ndungu@parent.school.edu',  role: 'Parent',  group: 'Grade 10A',      status: 'Active',    joined: 'Feb 2024', phone: '+254 700 111 007', dob: '1975-04-02' },
  { id: 8,  name: 'Sofia Abiodun',      email: 'sofia.a@school.edu',          role: 'Student', group: 'Grade 9D',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 008', dob: '2010-08-27' },
  { id: 9,  name: 'Mr. Samuel Bett',    email: 's.bett@school.edu',           role: 'Teacher', group: 'English Lit.',   status: 'Suspended', joined: 'Aug 2019', phone: '+254 700 111 009', dob: '1982-12-09' },
  { id: 10, name: 'Zawadi Chebet',      email: 'zawadi.c@school.edu',         role: 'Student', group: 'Grade 7A',       status: 'Active',    joined: 'Jan 2025', phone: '+254 700 111 010', dob: '2013-03-14' },
  { id: 11, name: 'Brian Omondi',       email: 'b.omondi@school.edu',         role: 'Student', group: 'Grade 9B',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 011', dob: '2010-05-19' },
  { id: 12, name: 'Ms. Alice Njeri',    email: 'a.njeri@school.edu',          role: 'Teacher', group: 'History',        status: 'Active',    joined: 'Aug 2023', phone: '+254 700 111 012', dob: '1988-02-23' },
  { id: 13, name: 'Cynthia Aoko',       email: 'c.aoko@school.edu',           role: 'Student', group: 'Grade 8A',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 013', dob: '2011-10-11' },
  { id: 14, name: 'Daniel Mwenda',      email: 'd.mwenda@parent.school.edu',  role: 'Parent',  group: 'Grade 8B',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 014', dob: '1979-07-07' },
  { id: 15, name: 'Esther Kamau',       email: 'e.kamau@school.edu',          role: 'Student', group: 'Grade 10B',      status: 'Inactive',  joined: 'Jan 2023', phone: '+254 700 111 015', dob: '2009-12-30' },
  { id: 16, name: 'Michael Kiprop',     email: 'm.kiprop@school.edu',         role: 'Student', group: 'Grade 11A',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 016', dob: '2008-02-18' },
  { id: 17, name: 'Sarah Chelangat',    email: 's.chelangat@school.edu',      role: 'Student', group: 'Grade 9C',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 017', dob: '2010-07-25' },
  { id: 18, name: 'Robert Kinyua',      email: 'r.kinyua@school.edu',         role: 'Teacher', group: 'Physics',        status: 'Active',    joined: 'Aug 2021', phone: '+254 700 111 018', dob: '1986-04-15' },
  { id: 19, name: 'Margaret Wairimu',   email: 'm.wairimu@school.edu',        role: 'Student', group: 'Grade 10C',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 019', dob: '2009-09-08' },
  { id: 20, name: 'John Mwangi',        email: 'j.mwangi@school.edu',         role: 'Student', group: 'Grade 8C',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 020', dob: '2011-06-30' },
  { id: 21, name: 'Dr. Susan Chepkorir', email: 's.chepkorir@school.edu',      role: 'Teacher', group: 'Biology',        status: 'Active',    joined: 'Jan 2020', phone: '+254 700 111 021', dob: '1983-10-12' },
  { id: 22, name: 'Joseph Njoroge',     email: 'j.njoroge@school.edu',        role: 'Student', group: 'Grade 7B',       status: 'Active',    joined: 'Jan 2025', phone: '+254 700 111 022', dob: '2013-01-20' },
  { id: 23, name: 'Rachel Akinyi',      email: 'r.akinyi@school.edu',         role: 'Student', group: 'Grade 9A',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 023', dob: '2010-11-03' },
  { id: 24, name: 'Samuel Odhiambo',    email: 's.odhiambo@school.edu',       role: 'Teacher', group: 'Chemistry',      status: 'Active',    joined: 'Aug 2022', phone: '+254 700 111 024', dob: '1987-06-09' },
  { id: 25, name: 'Faith Muthoni',      email: 'f.muthoni@school.edu',        role: 'Student', group: 'Grade 11B',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 025', dob: '2008-08-17' },
  { id: 26, name: 'Peter Waweru',       email: 'p.waweru@school.edu',         role: 'Student', group: 'Grade 8D',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 026', dob: '2011-12-01' },
  { id: 27, name: 'Mary Mbithe',        email: 'm.mbithe@school.edu',         role: 'Student', group: 'Grade 10D',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 027', dob: '2009-05-23' },
  { id: 28, name: 'James Gitau',        email: 'j.gitau@school.edu',          role: 'Teacher', group: 'Geography',      status: 'Active',    joined: 'Aug 2023', phone: '+254 700 111 028', dob: '1989-11-14' },
  { id: 29, name: 'Gladys Kemunto',     email: 'g.kemunto@school.edu',        role: 'Student', group: 'Grade 7C',       status: 'Active',    joined: 'Jan 2025', phone: '+254 700 111 029', dob: '2013-04-07' },
  { id: 30, name: 'Edwin Otieno',       email: 'e.otieno@school.edu',         role: 'Student', group: 'Grade 9E',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 030', dob: '2010-09-19' },
  { id: 31, name: 'Ruth Jepkosgei',     email: 'r.jepkosgei@school.edu',      role: 'Student', group: 'Grade 8E',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 031', dob: '2011-07-16' },
  { id: 32, name: 'Patrick Kangethe',   email: 'p.kangethe@school.edu',       role: 'Teacher', group: 'Mathematics',    status: 'Active',    joined: 'Aug 2020', phone: '+254 700 111 032', dob: '1984-03-28' },
  { id: 33, name: 'Diana Chelimo',      email: 'd.chelimo@school.edu',        role: 'Student', group: 'Grade 11D',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 033', dob: '2008-10-25' },
  { id: 34, name: 'Evans Mbugua',       email: 'e.mbugua@school.edu',         role: 'Student', group: 'Grade 10E',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 034', dob: '2009-01-09' },
  { id: 35, name: 'Joyce Akoth',        email: 'j.akoth@school.edu',          role: 'Student', group: 'Grade 9F',       status: 'Inactive',  joined: 'Jan 2023', phone: '+254 700 111 035', dob: '2010-04-29' },
  { id: 36, name: 'David Odongo',       email: 'd.odongo@school.edu',         role: 'Teacher', group: 'English',        status: 'Active',    joined: 'Aug 2021', phone: '+254 700 111 036', dob: '1986-12-05' },
  { id: 37, name: 'Priscilla Akinyi',   email: 'p.akinyi@school.edu',        role: 'Student', group: 'Grade 7D',       status: 'Active',    joined: 'Jan 2025', phone: '+254 700 111 037', dob: '2013-06-18' },
  { id: 38, name: 'Benjamin Kariuki',   email: 'b.kariuki@school.edu',        role: 'Student', group: 'Grade 8F',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 038', dob: '2011-08-12' },
  { id: 39, name: 'Anita Achieng',      email: 'a.achieng@school.edu',        role: 'Student', group: 'Grade 11E',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 039', dob: '2008-03-21' },
  { id: 40, name: 'Charles Kinyanjui',  email: 'c.kinyanjui@school.edu',      role: 'Teacher', group: 'History',        status: 'Suspended', joined: 'Aug 2019', phone: '+254 700 111 040', dob: '1982-08-15' },
  { id: 41, name: 'Nancy Wambui',       email: 'n.wambui@school.edu',         role: 'Student', group: 'Grade 10F',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 041', dob: '2009-11-27' },
  { id: 42, name: 'Collins Ochieng',    email: 'c.ochieng@school.edu',        role: 'Student', group: 'Grade 9G',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 042', dob: '2010-02-14' },
  { id: 43, name: 'Grace Ndanu',        email: 'g.ndanu@school.edu',          role: 'Student', group: 'Grade 8G',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 043', dob: '2011-09-04' },
  { id: 44, name: 'Timothy Mutua',      email: 't.mutua@school.edu',          role: 'Teacher', group: 'Geography',      status: 'Active',    joined: 'Aug 2023', phone: '+254 700 111 044', dob: '1988-05-30' },
  { id: 45, name: 'Jane Chepngetich',   email: 'j.chepngetich@school.edu',   role: 'Student', group: 'Grade 7E',       status: 'Active',    joined: 'Jan 2025', phone: '+254 700 111 045', dob: '2013-12-10' },
  { id: 46, name: 'Daniel Kiptoo',      email: 'd.kiptoo@school.edu',         role: 'Student', group: 'Grade 11F',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 046', dob: '2008-01-07' },
  { id: 47, name: 'Margaret Nyokabi',   email: 'm.nyokabi@school.edu',        role: 'Student', group: 'Grade 10G',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 047', dob: '2009-07-31' },
  { id: 48, name: 'Stephen Kioko',      email: 's.kioko@school.edu',          role: 'Teacher', group: 'Biology',        status: 'Active',    joined: 'Aug 2022', phone: '+254 700 111 048', dob: '1987-12-19' },
  { id: 49, name: 'Elizabeth Korir',    email: 'e.korir@school.edu',          role: 'Student', group: 'Grade 9H',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 049', dob: '2010-06-08' },
  { id: 50, name: 'Joseph Kamau',       email: 'j.kamau@school.edu',          role: 'Student', group: 'Grade 8H',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 050', dob: '2011-03-26' },
  { id: 51, name: 'Catherine Njeri',    email: 'c.njeri@school.edu',          role: 'Student', group: 'Grade 10H',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 051', dob: '2009-04-16' },
  { id: 52, name: 'Dr. Paul Ndirangu',  email: 'p.ndirangu@school.edu',       role: 'Teacher', group: 'Physics',        status: 'Active',    joined: 'Jan 2020', phone: '+254 700 111 052', dob: '1981-09-27' },
  { id: 53, name: 'Mary Kemunto',       email: 'm.kemunto@school.edu',        role: 'Student', group: 'Grade 11G',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 053', dob: '2008-11-11' },
  { id: 54, name: 'Peter Omondi',       email: 'p.omondi@school.edu',         role: 'Student', group: 'Grade 7F',       status: 'Active',    joined: 'Jan 2025', phone: '+254 700 111 054', dob: '2013-05-22' },
  { id: 55, name: 'Judith Nyawira',     email: 'j.nyawira@school.edu',        role: 'Student', group: 'Grade 9I',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 055', dob: '2010-08-03' },
  { id: 56, name: 'Samuel Maina',       email: 's.maina@school.edu',          role: 'Teacher', group: 'Chemistry',      status: 'Active',    joined: 'Aug 2021', phone: '+254 700 111 056', dob: '1985-10-20' },
  { id: 57, name: 'Doris Chepkemboi',   email: 'd.chepkemboi@school.edu',     role: 'Student', group: 'Grade 8I',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 057', dob: '2011-12-13' },
  { id: 58, name: 'Joshua Kipkorir',    email: 'j.kipkorir@school.edu',       role: 'Student', group: 'Grade 10I',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 058', dob: '2009-02-28' },
  { id: 59, name: 'Ruth Chepkoech',     email: 'r.chepkoech@school.edu',      role: 'Student', group: 'Grade 11H',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 059', dob: '2008-07-04' },
  { id: 60, name: 'Moses Njuguna',      email: 'm.njuguna@school.edu',        role: 'Teacher', group: 'Mathematics',    status: 'Active',    joined: 'Aug 2023', phone: '+254 700 111 060', dob: '1986-06-16' },
  { id: 61, name: 'Teresa Achieng',     email: 't.achieng@school.edu',        role: 'Student', group: 'Grade 9J',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 061', dob: '2010-10-09' },
  { id: 62, name: 'William Kiprotich',  email: 'w.kiprotich@school.edu',      role: 'Student', group: 'Grade 7G',       status: 'Active',    joined: 'Jan 2025', phone: '+254 700 111 062', dob: '2013-08-07' },
  { id: 63, name: 'Ann Muthoni',        email: 'a.muthoni@school.edu',        role: 'Student', group: 'Grade 8J',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 063', dob: '2011-02-15' },
  { id: 64, name: 'David Mwangi',       email: 'd.mwangi@school.edu',         role: 'Student', group: 'Grade 10J',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 064', dob: '2009-06-25' },
  { id: 65, name: 'Christine Wanjiru',  email: 'c.wanjiru@school.edu',        role: 'Student', group: 'Grade 11I',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 065', dob: '2008-04-08' },
  { id: 66, name: 'Joseph Ngugi',       email: 'j.ngugi@school.edu',          role: 'Teacher', group: 'English Lit.',   status: 'Active',    joined: 'Aug 2022', phone: '+254 700 111 066', dob: '1987-11-02' },
  { id: 67, name: 'Martha Chepngeno',   email: 'm.chepngeno@school.edu',      role: 'Student', group: 'Grade 9K',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 067', dob: '2010-03-31' },
  { id: 68, name: 'Patrick Nyamweya',   email: 'p.nyamweya@school.edu',       role: 'Student', group: 'Grade 7H',       status: 'Active',    joined: 'Jan 2025', phone: '+254 700 111 068', dob: '2013-10-14' },
  { id: 69, name: 'Sarah Muthoni',      email: 's.muthoni@school.edu',        role: 'Student', group: 'Grade 8K',       status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 069', dob: '2011-05-28' },
  { id: 70, name: 'Geoffrey Kipngeno',  email: 'g.kipngeno@school.edu',       role: 'Student', group: 'Grade 10K',      status: 'Active',    joined: 'Jan 2024', phone: '+254 700 111 070', dob: '2009-12-20' },
];

const MOCK_STATS = {
  students:   MOCK_USERS.filter(u => u.role === 'Student').length,
  teachers:   MOCK_USERS.filter(u => u.role === 'Teacher').length,
  admins:     MOCK_USERS.filter(u => u.role === 'Admin').length,
  parents:    MOCK_USERS.filter(u => u.role === 'Parent').length,
  totalStaff: MOCK_USERS.filter(u => u.role === 'Teacher' || u.role === 'Admin').length,
};

const MOCK_INVOICES = [
  { student: 'Amara Osei',      class: 'Grade 10A', title: 'Term 2 Fees',    total: 45000, paid: 45000 },
  { student: 'Fatima Al-Hassan',class: 'Grade 8B',  title: 'Term 2 Fees',    total: 42000, paid: 30000 },
  { student: 'Lily Wanjiku',    class: 'Grade 11C', title: 'Term 2 Fees',    total: 47000, paid: 47000 },
  { student: 'Sofia Abiodun',   class: 'Grade 9D',  title: 'Activity Levy',  total: 5000,  paid: 0     },
  { student: 'Zawadi Chebet',   class: 'Grade 7A',  title: 'Term 2 Fees',    total: 40000, paid: 20000 },
  { student: 'Michael Kiprop',  class: 'Grade 11A', title: 'Term 2 Fees',    total: 45000, paid: 45000 },
  { student: 'Sarah Chelangat', class: 'Grade 9C',  title: 'Activity Levy',  total: 5000,  paid: 3000  },
  { student: 'Margaret Wairimu',class: 'Grade 10C', title: 'Term 2 Fees',    total: 43000, paid: 43000 },
  { student: 'John Mwangi',     class: 'Grade 8C',  title: 'Term 2 Fees',    total: 41000, paid: 20000 },
  { student: 'Joseph Njoroge',  class: 'Grade 7B',  title: 'Term 2 Fees',    total: 39000, paid: 39000 },
  { student: 'Rachel Akinyi',   class: 'Grade 9A',  title: 'Activity Levy',  total: 5000,  paid: 5000  },
  { student: 'Faith Muthoni',   class: 'Grade 11B', title: 'Term 2 Fees',    total: 46000, paid: 30000 },
  { student: 'Peter Waweru',    class: 'Grade 8D',  title: 'Term 2 Fees',    total: 42000, paid: 42000 },
  { student: 'Mary Mbithe',     class: 'Grade 10D', title: 'Activity Levy',  total: 5000,  paid: 0     },
  { student: 'Gladys Kemunto',  class: 'Grade 7C',  title: 'Term 2 Fees',    total: 40000, paid: 25000 },
  { student: 'Edwin Otieno',    class: 'Grade 9E',  title: 'Term 2 Fees',    total: 44000, paid: 44000 },
  { student: 'Ruth Jepkosgei',  class: 'Grade 8E',  title: 'Term 2 Fees',    total: 41000, paid: 41000 },
  { student: 'Diana Chelimo',   class: 'Grade 11D', title: 'Activity Levy',  total: 5000,  paid: 2000  },
  { student: 'Evans Mbugua',    class: 'Grade 10E', title: 'Term 2 Fees',    total: 45000, paid: 35000 },
  { student: 'Joyce Akoth',     class: 'Grade 9F',  title: 'Term 2 Fees',    total: 43000, paid: 43000 },
  { student: 'Priscilla Akinyi',class: 'Grade 7D',  title: 'Term 2 Fees',    total: 39000, paid: 39000 },
  { student: 'Benjamin Kariuki',class: 'Grade 8F',  title: 'Activity Levy',  total: 5000,  paid: 5000  },
  { student: 'Anita Achieng',   class: 'Grade 11E', title: 'Term 2 Fees',    total: 47000, paid: 30000 },
  { student: 'Nancy Wambui',    class: 'Grade 10F', title: 'Term 2 Fees',    total: 44000, paid: 44000 },
  { student: 'Collins Ochieng', class: 'Grade 9G',  title: 'Term 2 Fees',    total: 42000, paid: 42000 },
  { student: 'Grace Ndanu',     class: 'Grade 8G',  title: 'Activity Levy',  total: 5000,  paid: 0     },
  { student: 'Jane Chepngetich',class: 'Grade 7E',  title: 'Term 2 Fees',    total: 40000, paid: 28000 },
  { student: 'Daniel Kiptoo',   class: 'Grade 11F', title: 'Term 2 Fees',    total: 46000, paid: 46000 },
  { student: 'Margaret Nyokabi',class: 'Grade 10G', title: 'Activity Levy',  total: 5000,  paid: 4000  },
  { student: 'Elizabeth Korir', class: 'Grade 9H',  title: 'Term 2 Fees',    total: 43000, paid: 43000 },
  { student: 'Joseph Kamau',    class: 'Grade 8H',  title: 'Term 2 Fees',    total: 41000, paid: 22000 },
  { student: 'Catherine Njeri', class: 'Grade 10H', title: 'Term 2 Fees',    total: 45000, paid: 45000 },
  { student: 'Mary Kemunto',    class: 'Grade 11G', title: 'Activity Levy',  total: 5000,  paid: 3000  },
  { student: 'Peter Omondi',    class: 'Grade 7F',  title: 'Term 2 Fees',    total: 39000, paid: 39000 },
  { student: 'Judith Nyawira',  class: 'Grade 9I',  title: 'Term 2 Fees',    total: 44000, paid: 35000 },
  { student: 'Doris Chepkemboi',class: 'Grade 8I',  title: 'Term 2 Fees',    total: 42000, paid: 42000 },
  { student: 'Joshua Kipkorir', class: 'Grade 10I', title: 'Activity Levy',  total: 5000,  paid: 5000  },
  { student: 'Ruth Chepkoech',  class: 'Grade 11H', title: 'Term 2 Fees',    total: 47000, paid: 31000 },
  { student: 'Teresa Achieng',  class: 'Grade 9J',  title: 'Term 2 Fees',    total: 43000, paid: 43000 },
  { student: 'William Kiprotich',class: 'Grade 7G', title: 'Term 2 Fees',    total: 40000, paid: 40000 },
  { student: 'Ann Muthoni',     class: 'Grade 8J',  title: 'Activity Levy',  total: 5000,  paid: 0     },
  { student: 'David Mwangi',    class: 'Grade 10J', title: 'Term 2 Fees',    total: 45000, paid: 38000 },
  { student: 'Christine Wanjiru',class: 'Grade 11I',title: 'Term 2 Fees',    total: 46000, paid: 46000 },
  { student: 'Martha Chepngeno',class: 'Grade 9K',  title: 'Activity Levy',  total: 5000,  paid: 2000  },
  { student: 'Patrick Nyamweya',class: 'Grade 7H',  title: 'Term 2 Fees',    total: 39000, paid: 39000 },
  { student: 'Sarah Muthoni',   class: 'Grade 8K',  title: 'Term 2 Fees',    total: 41000, paid: 33000 },
  { student: 'Geoffrey Kipngeno',class: 'Grade 10K',title: 'Term 2 Fees',    total: 44000, paid: 44000 },
];

const MOCK_ATTENDANCE = {
  date: new Date().toLocaleDateString('en-KE', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }),
  present: 55,
  absent: 12,
  total: 67,
};

const MOCK_ALUMNI = [
  { id: 1,  name: 'Kevin Mwangi',      email: 'kevin.mwangi@gmail.com',      gradYear: 2020, program: 'Science',          status: 'Employed',    occupation: 'Software Engineer',      employer: 'Safaricom PLC',         phone: '+254 711 200 001', location: 'Nairobi' },
  { id: 2,  name: 'Sharon Atieno',     email: 'sharon.atieno@gmail.com',     gradYear: 2021, program: 'Arts',             status: 'Studying',    occupation: 'BSc Computer Science',   employer: 'University of Nairobi', phone: '+254 711 200 002', location: 'Nairobi' },
  { id: 3,  name: 'Felix Kariuki',     email: 'felix.kariuki@outlook.com',   gradYear: 2019, program: 'Commerce',         status: 'Employed',    occupation: 'Accountant',             employer: 'KCB Bank Kenya',        phone: '+254 711 200 003', location: 'Mombasa' },
  { id: 4,  name: 'Brenda Onyango',    email: 'brenda.onyango@gmail.com',    gradYear: 2022, program: 'Science',          status: 'Studying',    occupation: 'MBChB Medicine',         employer: 'Kenyatta University',   phone: '+254 711 200 004', location: 'Nairobi' },
  { id: 5,  name: 'Victor Kipchoge',   email: 'victor.kipchoge@gmail.com',   gradYear: 2018, program: 'Technical',        status: 'Self-employed', occupation: 'Electrician',          employer: 'VK Solutions',          phone: '+254 711 200 005', location: 'Eldoret' },
  { id: 6,  name: 'Nancy Wambui',      email: 'nancy.wambui@yahoo.com',      gradYear: 2021, program: 'Arts',             status: 'Employed',    occupation: 'Journalist',             employer: 'Nation Media Group',    phone: '+254 711 200 006', location: 'Nairobi' },
  { id: 7,  name: 'George Ochieng',    email: 'george.ochieng@gmail.com',    gradYear: 2020, program: 'Commerce',         status: 'Unemployed',  occupation: '—',                      employer: '—',                     phone: '+254 711 200 007', location: 'Kisumu' },
  { id: 8,  name: 'Patricia Mutua',    email: 'patricia.mutua@gmail.com',    gradYear: 2019, program: 'Science',          status: 'Employed',    occupation: 'Civil Engineer',         employer: 'Kenya Roads Board',     phone: '+254 711 200 008', location: 'Nairobi' },
  { id: 9,  name: 'Samuel Cheruiyot',  email: 's.cheruiyot@outlook.com',     gradYear: 2022, program: 'Technical',        status: 'Studying',    occupation: 'Diploma IT',             employer: 'Strathmore University', phone: '+254 711 200 009', location: 'Nakuru' },
  { id: 10, name: 'Diana Achieng',     email: 'diana.achieng@gmail.com',     gradYear: 2018, program: 'Arts',             status: 'Employed',    occupation: 'Graphic Designer',       employer: 'Ogilvy Africa',         phone: '+254 711 200 010', location: 'Nairobi' },
  { id: 11, name: 'Moses Kamotho',     email: 'moses.kamotho@gmail.com',     gradYear: 2023, program: 'Science',          status: 'Studying',    occupation: 'BSc Nursing',            employer: 'Moi University',        phone: '+254 711 200 011', location: 'Eldoret' },
  { id: 12, name: 'Irene Njoki',       email: 'irene.njoki@gmail.com',       gradYear: 2017, program: 'Commerce',         status: 'Employed',    occupation: 'Marketing Manager',      employer: 'Equity Bank',           phone: '+254 711 200 012', location: 'Nairobi' },
  { id: 13, name: 'Alex Otieno',       email: 'alex.otieno@gmail.com',       gradYear: 2023, program: 'Arts',             status: 'Unemployed',  occupation: '—',                      employer: '—',                     phone: '+254 711 200 013', location: 'Kisumu' },
  { id: 14, name: 'Caroline Njeru',    email: 'caroline.njeru@outlook.com',  gradYear: 2016, program: 'Science',          status: 'Employed',    occupation: 'Pharmacist',             employer: 'Aga Khan Hospital',     phone: '+254 711 200 014', location: 'Nairobi' },
  { id: 15, name: 'Dennis Wekesa',     email: 'dennis.wekesa@gmail.com',     gradYear: 2021, program: 'Technical',        status: 'Self-employed', occupation: 'Plumber',              employer: 'DW Services',           phone: '+254 711 200 015', location: 'Kakamega' },
  { id: 16, name: 'Lydia Chebet',      email: 'lydia.chebet@gmail.com',      gradYear: 2020, program: 'Science',          status: 'Employed',    occupation: 'Lab Technician',         employer: 'KEMRI',                 phone: '+254 711 200 016', location: 'Kisumu' },
  { id: 17, name: 'Frank Njoroge',     email: 'frank.njoroge@gmail.com',     gradYear: 2019, program: 'Commerce',         status: 'Employed',    occupation: 'Banker',                 employer: 'Standard Chartered',    phone: '+254 711 200 017', location: 'Nairobi' },
  { id: 18, name: 'Mercy Auma',        email: 'mercy.auma@yahoo.com',        gradYear: 2022, program: 'Arts',             status: 'Studying',    occupation: 'BA Education',           employer: 'Maseno University',     phone: '+254 711 200 018', location: 'Kisumu' },
  { id: 19, name: 'Edwin Ndiema',      email: 'edwin.ndiema@gmail.com',      gradYear: 2018, program: 'Commerce',         status: 'Employed',    occupation: 'Business Analyst',       employer: 'PwC Kenya',             phone: '+254 711 200 019', location: 'Nairobi' },
  { id: 20, name: 'Faith Chepkwony',   email: 'faith.chepkwony@yahoo.com',   gradYear: 2021, program: 'Science',          status: 'Studying',    occupation: 'BSc Biotechnology',      employer: 'Jomo Kenyatta University', phone: '+254 711 200 020', location: 'Kisumu' },
  { id: 21, name: 'John Macharia',     email: 'john.macharia@gmail.com',     gradYear: 2020, program: 'Technical',        status: 'Self-employed', occupation: 'IT Consultant',         employer: 'JM Tech Solutions',     phone: '+254 711 200 021', location: 'Nakuru' },
  { id: 22, name: 'Rose Akinyi',       email: 'rose.akinyi@gmail.com',       gradYear: 2019, program: 'Arts',             status: 'Employed',    occupation: 'HR Manager',             employer: 'Kenyatta Hospital',     phone: '+254 711 200 022', location: 'Nairobi' },
  { id: 23, name: 'David Kiprop',      email: 'david.kiprop@outlook.com',    gradYear: 2023, program: 'Commerce',         status: 'Unemployed',  occupation: '—',                      employer: '—',                     phone: '+254 711 200 023', location: 'Eldoret' },
  { id: 24, name: 'Maryanne Mwangi',   email: 'maryanne.mwangi@gmail.com',   gradYear: 2017, program: 'Science',          status: 'Employed',    occupation: 'Data Scientist',         employer: 'Microsoft',             phone: '+254 711 200 024', location: 'Nairobi' },
  { id: 25, name: 'Peter Njoroge',     email: 'peter.njoroge@gmail.com',     gradYear: 2022, program: 'Technical',        status: 'Self-employed', occupation: 'Web Developer',         employer: 'PN Web Solutions',      phone: '+254 711 200 025', location: 'Mombasa' },
  { id: 26, name: 'Alice Wanjiru',     email: 'alice.wanjiru@gmail.com',     gradYear: 2021, program: 'Arts',             status: 'Employed',    occupation: 'Teacher',                employer: 'Brookhouse School',     phone: '+254 711 200 026', location: 'Nairobi' },
  { id: 27, name: 'Samuel Otieno',     email: 'samuel.otieno@yahoo.com',     gradYear: 2018, program: 'Science',          status: 'Studying',    occupation: 'MSc Environmental Science', employer: 'University of Nairobi', phone: '+254 711 200 027', location: 'Kisumu' },
  { id: 28, name: 'Grace Kemunto',     email: 'grace.kemunto@gmail.com',     gradYear: 2020, program: 'Commerce',         status: 'Employed',    occupation: 'Financial Analyst',      employer: 'Deloitte',              phone: '+254 711 200 028', location: 'Nairobi' },
  { id: 29, name: 'James Mwangi',      email: 'james.mwangi@gmail.com',      gradYear: 2023, program: 'Technical',        status: 'Self-employed', occupation: 'Network Engineer',      employer: 'JMN Networks',          phone: '+254 711 200 029', location: 'Nakuru' },
  { id: 30, name: 'Lydia Achieng',     email: 'lydia.achieng@gmail.com',     gradYear: 2019, program: 'Science',          status: 'Employed',    occupation: 'Nurse',                  employer: 'Aga Khan Hospital',     phone: '+254 711 200 030', location: 'Nairobi' },
  { id: 31, name: 'Josephine Chebet',  email: 'josephine.chebet@gmail.com',  gradYear: 2021, program: 'Arts',             status: 'Studying',    occupation: 'MPhil Literature',      employer: 'University of Nairobi', phone: '+254 711 200 031', location: 'Nairobi' },
  { id: 32, name: 'Alex Kipkemboi',    email: 'alex.kipkemboi@outlook.com',  gradYear: 2020, program: 'Commerce',         status: 'Employed',    occupation: 'Accountant',             employer: 'PricewaterhouseCoopers', phone: '+254 711 200 032', location: 'Mombasa' },
  { id: 33, name: 'Maria Wambui',      email: 'maria.wambui@gmail.com',      gradYear: 2018, program: 'Science',          status: 'Unemployed',  occupation: '—',                      employer: '—',                     phone: '+254 711 200 033', location: 'Eldoret' },
  { id: 34, name: 'Stephen Ochieng',   email: 'stephen.ochieng@gmail.com',   gradYear: 2022, program: 'Technical',        status: 'Employed',    occupation: 'Cloud Architect',        employer: 'Amazon Web Services',   phone: '+254 711 200 034', location: 'Nairobi' },
  { id: 35, name: 'Catherine Nderitu', email: 'catherine.nderitu@gmail.com', gradYear: 2021, program: 'Arts',             status: 'Self-employed', occupation: 'Freelance Writer',      employer: 'Self',                  phone: '+254 711 200 035', location: 'Kisumu' },
  { id: 36, name: 'Daniel Wanjala',    email: 'daniel.wanjala@gmail.com',    gradYear: 2019, program: 'Science',          status: 'Studying',    occupation: 'PhD Physics',            employer: 'University of Nairobi', phone: '+254 711 200 036', location: 'Nairobi' },
  { id: 37, name: 'Ruth Chepngeno',    email: 'ruth.chepngeno@yahoo.com',    gradYear: 2020, program: 'Commerce',         status: 'Employed',    occupation: 'Marketing Specialist',   employer: 'Diageo',                phone: '+254 711 200 037', location: 'Nairobi' },
  { id: 38, name: 'Bernard Kinyua',    email: 'bernard.kinyua@gmail.com',    gradYear: 2023, program: 'Technical',        status: 'Self-employed', occupation: 'UI/UX Designer',        employer: 'BK Design Studio',      phone: '+254 711 200 038', location: 'Nakuru' },
  { id: 39, name: 'Judy Auma',         email: 'judy.auma@gmail.com',         gradYear: 2018, program: 'Arts',             status: 'Employed',    occupation: 'Project Manager',        employer: 'Google',                phone: '+254 711 200 039', location: 'Nairobi' },
  { id: 40, name: 'Michael Kiplangat', email: 'michael.kiplangat@gmail.com', gradYear: 2022, program: 'Science',          status: 'Unemployed',  occupation: '—',                      employer: '—',                     phone: '+254 711 200 040', location: 'Eldoret' },
  { id: 41, name: 'Sarah Nduta',       email: 'sarah.nduta@gmail.com',       gradYear: 2021, program: 'Commerce',         status: 'Employed',    occupation: 'Management Consultant',  employer: 'McKinsey & Company',    phone: '+254 711 200 041', location: 'Nairobi' },
  { id: 42, name: 'Joseph Waweru',     email: 'joseph.waweru@outlook.com',   gradYear: 2019, program: 'Technical',        status: 'Self-employed', occupation: 'Database Administrator', employer: 'JWA Solutions',         phone: '+254 711 200 042', location: 'Mombasa' },
  { id: 43, name: 'Margaret Kiprop',   email: 'margaret.kiprop@gmail.com',   gradYear: 2020, program: 'Arts',             status: 'Studying',    occupation: 'MA Sociology',           employer: 'University of Nairobi', phone: '+254 711 200 043', location: 'Nairobi' },
  { id: 44, name: 'Samuel Kinyanjui',  email: 'samuel.kinyanjui@gmail.com',  gradYear: 2023, program: 'Science',          status: 'Employed',    occupation: 'Software Developer',      employer: 'Safaricom PLC',         phone: '+254 711 200 044', location: 'Nairobi' },
  { id: 45, name: 'Jane Akinyi',       email: 'jane.akinyi@gmail.com',       gradYear: 2018, program: 'Commerce',         status: 'Unemployed',  occupation: '—',                      employer: '—',                     phone: '+254 711 200 045', location: 'Kisumu' },
  { id: 46, name: 'David Omondi',      email: 'david.omondi@gmail.com',      gradYear: 2021, program: 'Technical',        status: 'Employed',    occupation: 'DevOps Engineer',        employer: 'Microsoft',             phone: '+254 711 200 046', location: 'Nairobi' },
  { id: 47, name: 'Mary Chebet',       email: 'mary.chebet@yahoo.com',       gradYear: 2020, program: 'Science',          status: 'Self-employed', occupation: 'Life Coach',            employer: 'Self',                  phone: '+254 711 200 047', location: 'Nakuru' },
  { id: 48, name: 'Charles Mwangi',    email: 'charles.mwangi@gmail.com',    gradYear: 2022, program: 'Arts',             status: 'Studying',    occupation: 'MSc Psychology',        employer: 'University of Nairobi', phone: '+254 711 200 048', location: 'Nairobi' },
  { id: 49, name: 'Elizabeth Njoroge', email: 'elizabeth.njoroge@gmail.com', gradYear: 2019, program: 'Commerce',         status: 'Employed',    occupation: 'Supply Chain Manager',   employer: 'DHL',                   phone: '+254 711 200 049', location: 'Nairobi' },
  { id: 50, name: 'Geoffrey Kipngeno', email: 'geoffrey.kipngeno@gmail.com', gradYear: 2023, program: 'Science',          status: 'Self-employed', occupation: 'Digital Marketer',      employer: 'GK Digital',            phone: '+254 711 200 050', location: 'Mombasa' },
  { id: 51, name: 'Grace Auma',        email: 'grace.auma@gmail.com',        gradYear: 2017, program: 'Technical',        status: 'Employed',    occupation: 'Cybersecurity Analyst',  employer: 'KCB Bank Kenya',        phone: '+254 711 200 051', location: 'Nairobi' },
  { id: 52, name: 'Peter Kariuki',     email: 'peter.kariuki@outlook.com',   gradYear: 2021, program: 'Arts',             status: 'Unemployed',  occupation: '—',                      employer: '—',                     phone: '+254 711 200 052', location: 'Eldoret' },
  { id: 53, name: 'Lucy Wanjiku',      email: 'lucy.wanjiku@gmail.com',      gradYear: 2020, program: 'Commerce',         status: 'Employed',    occupation: 'Banker',                 employer: 'Equity Bank',           phone: '+254 711 200 053', location: 'Nairobi' },
  { id: 54, name: 'Samuel Ndegwa',     email: 'samuel.ndegwa@gmail.com',     gradYear: 2022, program: 'Science',          status: 'Studying',    occupation: 'MSc Data Science',       employer: 'Strathmore University', phone: '+254 711 200 054', location: 'Nairobi' },
  { id: 55, name: 'Rose Kiprop',       email: 'rose.kiprop@gmail.com',       gradYear: 2019, program: 'Technical',        status: 'Self-employed', occupation: 'Mobile Developer',       employer: 'RK Apps',               phone: '+254 711 200 055', location: 'Kisumu' },
  { id: 56, name: 'Michael Ochieng',   email: 'michael.ochieng@gmail.com',   gradYear: 2023, program: 'Arts',             status: 'Employed',    occupation: 'Content Creator',        employer: 'BBC Kenya',             phone: '+254 711 200 056', location: 'Nairobi' },
  { id: 57, name: 'Sarah Chepkwony',   email: 'sarah.chepkwony@gmail.com',   gradYear: 2018, program: 'Science',          status: 'Unemployed',  occupation: '—',                      employer: '—',                     phone: '+254 711 200 057', location: 'Nakuru' },
  { id: 58, name: 'Joseph Ouma',       email: 'joseph.ouma@gmail.com',       gradYear: 2021, program: 'Commerce',         status: 'Employed',    occupation: 'Financial Advisor',      employer: 'Stanbic Bank',          phone: '+254 711 200 058', location: 'Nairobi' },
  { id: 59, name: 'Grace Njoroge',     email: 'grace.njoroge@yahoo.com',     gradYear: 2020, program: 'Technical',        status: 'Self-employed', occupation: 'Video Editor',          employer: 'GN Productions',        phone: '+254 711 200 059', location: 'Mombasa' },
  { id: 60, name: 'David Mwangi',      email: 'david.mwangi@gmail.com',      gradYear: 2022, program: 'Science',          status: 'Studying',    occupation: 'MSc Biotechnology',      employer: 'Kenyatta University',   phone: '+254 711 200 060', location: 'Nairobi' },
];

const MOCK_ALUMNI_STATS = {
  total:        MOCK_ALUMNI.length,
  employed:     MOCK_ALUMNI.filter(a => a.status === 'Employed').length,
  studying:     MOCK_ALUMNI.filter(a => a.status === 'Studying').length,
  selfEmployed: MOCK_ALUMNI.filter(a => a.status === 'Self-employed').length,
  unemployed:   MOCK_ALUMNI.filter(a => a.status === 'Unemployed').length,
};